### ISSUE TITLE
Adding IDNs with pre-existing zone fails

### ISSUE THREAD

**Issue by edisim** [apisnetworks/apnscp-dns-cloudflare#1]
I tried adding a un-punycoded domain as an alias and the Cloudflare provider failed to verify if the zone for it already existed, so it tried to create it instead.

To reproduce:
- add (punycoded) zone/domain to Cloudflare
- create API key with editing permission for said domain
- use API key when adding alias to site in ApisCP

Workaround:
- add zone creating/editing permission to API key
⇾ Cloudflare provider tries to create a new zone but seems to use the existing one ultimately

**Comment by msaladna** [comment]
I'm not sure if I understand this fully. Can you provide an error message either here or mail to matt@apisnetworks.com. When using API tokens, both Zone.DNS and Zone.Zone [require edit permissions](https://docs.apiscp.com/admin/dns/Cloudflare/#using-api-tokens).

API keys don't have permission scopes and instead give full access. They're hexadecimal + email. API tokens are a-Z0-9 and do not require your email when setting up.

**Comment by edisim** [comment]
You were right about the permissons, I only had Zone.DNS active in this case. 🙄

Thanks and sorry for the the delay.
